<a href="https://colab.research.google.com/github/BradleyConlin/TensorFlow2_Intro/blob/main/QS_TensorFlow2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 0s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.8999403 , -0.16713673, -0.40261823,  0.74013984,  0.5992226 ,
         0.17445469,  0.71278536, -0.5032282 ,  0.26564816, -0.51909125]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.18050773, 0.06209693, 0.04906839, 0.15384923, 0.13362747,
        0.08738188, 0.14969781, 0.04437185, 0.09572519, 0.04367352]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.4374673

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.4807 - accuracy: 0.8596
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1598 - accuracy: 0.9517
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1104 - accuracy: 0.9672
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0874 - accuracy: 0.9736
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0763 - accuracy: 0.9761


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0723 - accuracy: 0.9780


[0.07230118662118912, 0.9779999852180481]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.8625760e-08, 1.1656059e-08, 9.6574695e-06, 4.0556453e-05,
        5.6717395e-11, 1.8753878e-08, 6.1633797e-12, 9.9994767e-01,
        1.1336169e-07, 2.0789321e-06],
       [3.9514435e-07, 2.8604272e-04, 9.9970347e-01, 7.5277812e-06,
        8.9657982e-16, 1.5888412e-06, 6.4580792e-07, 4.6837360e-13,
        3.2294480e-07, 2.1090153e-14],
       [1.2634374e-07, 9.9606764e-01, 6.5716857e-04, 5.0328465e-05,
        4.8672562e-04, 4.9014954e-05, 1.1793148e-04, 2.0443855e-03,
        5.2467728e-04, 1.9033546e-06],
       [9.9987328e-01, 3.3890753e-08, 8.9332234e-06, 1.1420483e-07,
        1.1973016e-07, 7.5842763e-06, 5.5853314e-05, 4.9614850e-05,
        4.2508042e-08, 4.3859154e-06],
       [5.7420189e-06, 9.6703348e-09, 1.6929218e-05, 1.0130448e-07,
        9.9291623e-01, 3.5186492e-06, 2.9106714e-06, 9.8818867e-04,
        3.2477027e-07, 6.0659465e-03]], dtype=float32)>